controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Logs;
use app\models\RegisterForm;
use app\models\ResetPasswordForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Project;
use app\models\Board;
use app\models\Sprints;
use app\models\Tasks;
use app\models\Signup;
use app\models\Users;
use app\models\Comment;
use app\models\Companies;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public $wrapperClass;

    public function behaviors()
    {
        return [
            'companies' => [
                'class' => \app\filters\CompaniesFilter::class,
                'only' => ['dashboard', 'boards-client', 'board-detail-sprint', 'boards-project', 'boards-sprint'],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['dashboard', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            /*'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) { 
            return $this->redirect('site/boards-project');
        }else
        {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Регистрирует нового пользователя
     * @return string|Response
     */
    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $log = new Logs([
            'user_id' => null,
            'event_datetime' => date('Y-m-d H:i:s'),
            'event' => Logs::EVENT_USER_OPEN_REGISTRATION_PAGE,
        ]);
        $log->description = $log->generateEventDescription();
        $log->save();

        $this->layout = 'main-login';

        $model = new RegisterForm();

        if($model->load(Yii::$app->request->post()) && $model->register())
        {
            //Yii::$app->session->setFlash('register_success', 'Регистрация прошла успешно. Пожалуйста, авторизируйтесь');
            $login_model = new LoginForm();
            $login_model->username = $model->login;
            $login_model->password = $model->password;
            if ($login_model->login()) {
                Companies::setDefaultValues();
                return $this->goBack();
            }
            else return $this->redirect(['login']);
        } else {
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return string|Response
     */
    public function actionReset()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'main-login';

        $model = new ResetPasswordForm();

        if($model->load(Yii::$app->request->post()) && $model->reset())
        {
            Yii::$app->session->setFlash('register_success', 'На вашу почту был выслан временный пароль. Воспользуйтесь им для авторизации');
            return $this->redirect(['login']);
        } else {
            return $this->render('reset', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Рабочий стол
     * @return Response|string
     */
// через этот екшн заходим на Рабочий стол
    public function actionDashboard()
    {

        if (Yii::$app->user->isGuest)   return $this->redirect(['site/login']);

        $tip = Yii::$app->user->identity->type;
        $user_id = Yii::$app->user->identity->id;

        if($tip == 5)
        {
            $all_tasks = Tasks::find()->where(['executor' => $user_id ])->all();
        }
        if($tip == 3)
        {
            $all_tasks = Tasks::find()->where(['manager_project' => $user_id])->all();
        }
        if($tip == 1 | $tip == 6)
        {
            $user = Users::findOne($user_id);
            if($user->creator != null) $all_tasks = Tasks::find()->where(['company_id' => $user->creator ])->all();
            else $all_tasks = Tasks::find()->where(['company_id' => $user_id])->all();
        }
        if($tip == 4)
        {
            $tasks = Project::find()->where(['client' => $user_id])->all();
            $result = [];
            foreach ($tasks as $value) {
                $result [] = $value->id;
            }
            $result = array_unique($result);
            $all_tasks = Tasks::find()->where(['project' => $result])->all();
        }

        
        $user = Users::findOne($user_id);
        if($tip == 3) $project = Project::find()->where(['responsible' => $user_id])->all();
        if($tip == 4) $project = Project::find()->where(['client' => $user_id])->all();
        if($tip == 5) {
            $all_tasks = Tasks::find()->where(['executor' => $user_id ])->all();
            $array = [];
            foreach ($all_tasks as $value) {
                $array[] = $value->project;
            }
            $project = Project::find()->where(['id' => array_unique($array)])->all();
        }
        if($tip == 1 | $tip == 6 | $tip == 0) $project = Project::find()->all();

        $all = 0; $worked = 0; $ready = 0;
        foreach ($project as $value) {
            $all++;
            if($value->status == 3) $worked++;
            if($value->status == 1) $ready++;
        }
        $result  = [
            'all' => $all,
            'worked' => $worked,
            'ready' => $ready,
        ]; 

        $users = Users::find()->where([ 'company_id' => Yii::$app->user->identity->getCompany() ])->all();
        $array = [];
        foreach ($users as $value) {
            $array [] = $value->id;
        }

        $comments = Comment::find()->where(['created_by' => $array ])->orderBy(['created_at' => SORT_DESC])->all();

        $comment = [];
        foreach ($comments as $value) {
            $user = Users::findOne($value->created_by);
            $task = Tasks::findOne($value->entity);
            $q=0;
            if($tip == 5 && $task->executor == $user_id) $q=1;
            if($tip == 4 && $task->project0->client == $user_id) $q=1;
            if($tip == 3 && $task->manager_project == $user_id) $q=1;
            if($tip == 1 | $tip == 6 | $tip == 0) $q=1;

            if($q==1){
                $name = 'Unknown';
                $task_title = 'Unknown';
                if($user != null) 
                {
                    if($user->type == 1) $name = 'Администратор';
                    if($user->type == 2) $name = 'Аналитик';
                    if($user->type == 3) $name = 'Менеджер проекта';
                    if($user->type == 4) $name = 'Клиент';
                    if($user->type == 5) $name = 'Программист';
                    if($user->type == 6) $name = 'Компания';
                }
                if($task != null) $task_title = $task->task_title;
                $comment [] = [
                    'user' => $name,
                    'title' => $task_title,
                    'text' => $value->text,
                    'id' => $user->id,
                ];
            }
        }  

        $all = 0; $worked = 0; $ready = 0;
        $total_hour = 0;

        foreach ($all_tasks as $task) {
            $all++;
            if($task->stage0->status == 2) $worked++;
            if($task->stage0->status == 3) $ready++;  
            if($task->stage0->status == 3) $total_hour += $task->time_fact;      
        } 
        $result1  = [
            'all' => $all,
            'worked' => $worked,
            'ready' => $ready,
        ];     

        return $this->render('dashboard', [
            'all_tasks' => $result1,
            'result' => $result,
            'comment' => $comment,
            'total_hour' => $total_hour,
            'tasks' => $all_tasks,
        ]);
    }


    /**
     * Авторизация
     * @return string|Response
     */
    public function actionSign()
    {
        $this->redirect(['register']);
        /*$model = new Signup();
        if ($model->load(Yii::$app->request->post())) {

            $user = new Users();
            $user->fio = $model->fio;
            $user->login = $model->email;
            $user->password = $model->password;
            $user->dostup = 1;
            $user->type = 6;
            if($user->save())
            {   
                $msg  = 'Заявка c сайта Control \n Название компании: '. $model->fio .' Логин: '.$model->email. ' Пароль: '. $model->password;
                $ch = curl_init('https://api.telegram.org/bot474474429:AAEDvb8ifBsjAEYcLBeCzxKsFwk-XxHpM0s/sendMessage?chat_id=247187885&parse_mode=html&text='.$msg);
                // устанавлваем даные для отправки
                curl_setopt($ch, CURLOPT_POSTFIELDS, '11111');

views/yii2-app/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;

?>
<div class="site-error">

    <!-- begin error -->
    <div class="error">
        <div class="error-code m-b-10"><?=$exception->name?> <i class="fa fa-warning"></i></div>
        <div class="error-content">
            <div class="error-message"><?=$exception->getMessage()?></div>
            <div class="error-desc m-b-20">
                Если это ошибка сервера. <br>
                Свяжитесь с тех поддержкой.
            </div>
        </div>
    </div>
    <!-- end error -->

</div>

views/yii2-app/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login bg-black animated fadeInDown">
    <!-- begin brand -->
    <div class="login-header">
        <div class="brand">
            <span class="logo"></span> Control Project
            <small>Введите данные для авторизации</small>
        </div>
        <div class="icon">
            <i class="fa fa-sign-in"></i>
        </div>
    </div>
    <!-- end brand -->
    <div class="login-content">
        <?php if(Yii::$app->session->hasFlash('register_success')): ?>
            <p>
            <div class="alert alert-success show m-b-0">
                <span class="close" data-dismiss="alert">×</span>
                <strong>Успех!</strong>
                <?=Yii::$app->session->getFlash('register_success')?>
            </div>
            </p>
        <?php endif; ?>
        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['value'=>'admin','placeholder' => $model->getAttributeLabel('email'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['value'=>'admin','placeholder' => $model->getAttributeLabel('password'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <div class="row">
            <div class="col-md-8">
                <?= $form->field($model, 'rememberMe')->checkbox()->label('Запомни меня') ?>
            </div>
            <!-- <div class="col-md-4" style=" float: right;  margin-top: 10px; ">
                <?php // Html::a('Регистрация', ['site/sign', ]);?>                
            </div> -->

            <div class="login-buttons">
                <?= Html::submitButton('Вход', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
                <p style="display: inline-block; width: 100%;">
                    <?= Html::a('Востановить пароль', ['reset'], ['class' => 'pull-left', 'style' => 'display: inline-block; margin-top: 20px;color: gray;']); ?>
                    <?= Html::a('Зарегистрироваться', ['register'], ['class' => 'pull-right', 'style' => 'display: inline-block; margin-top: 20px;color: gray;']); ?>
                </p>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/yii2-app/site/register.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var $model \app\models\RegisterForm
 */

$this->title = 'Регистрация';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-user form-control-feedback'></span>"
];
$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-earphone form-control-feedback'></span>"
];
$fieldOptions3 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];
$fieldOptions4 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-asterisk form-control-feedback'></span>"
];
$fieldOptions5 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<i class='fa fa-vk form-control-feedback'></i>"
];
$fieldOptions6 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon glyphicon-ruble form-control-feedback'></span>"
];
?>

<div class="login bg-black animated fadeInDown">
    <!-- begin brand -->
    <div class="login-header">
        <div class="brand">
            <span class="logo"></span>  ТЕО-CONTROL
            <small>Введите данные для регистрации <i class="fa fa-users"></i> </small>
        </div>
        <div class="icon">
            <i class="fa fa-sign-in"></i>
        </div>
    </div>
    <!-- end brand -->
    <div class="login-content">
        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
        <?= $form
            ->field($model, 'fio', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('fio'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'rate_id', $fieldOptions6)
            ->label(false)
            ->dropDownList(\yii\helpers\ArrayHelper::map(\app\models\Rates::find()->all(), 'id', 'name'), ['placeholder' => $model->getAttributeLabel('rate_id'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'phone', $fieldOptions2)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('phone'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'login', $fieldOptions3)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('login'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'password', $fieldOptions4)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'vk_href', $fieldOptions5)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('vk_href'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
            <div class="login-buttons">
                <?= Html::submitButton('Регистрация', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/yii2-app/site/reset.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var $model \app\models\RegisterForm
 */

$this->title = 'Регистрация';

$fieldOptions = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];
?>

<div class="login bg-black animated fadeInDown">
    <!-- begin brand -->
    <div class="login-header">
        <div class="brand">
            <span class="logo"></span>  ТЕО-CONTROL
            <small>Введите данные для востановления пароля</small>
        </div>
        <div class="icon">
            <i class="fa fa-sign-in"></i>
        </div>
    </div>
    <!-- end brand -->
    <div class="login-content">
        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
        <?= $form
            ->field($model, 'login', $fieldOptions)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('login'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <div class="login-buttons">
            <?= Html::submitButton('Востановить', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/yii2-app/site/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login bg-black animated fadeInDown">
    <!-- begin brand -->
    <div class="login-header">
        <div class="brand">
            <span class="logo"></span> Регистрация
            <small>Регистрационное окно для компании</small>
        </div>
        <div class="icon">
            <i class="fa fa-sign-in"></i>
        </div>
    </div>
    <!-- end brand -->
    <div class="login-content">
        <?php $form = ActiveForm::begin(); ?>
        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-md-12">
                         <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-md-12">
                        <?= $form->field($model, 'password')->textInput(['maxlength' => true]) ?>
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Зарегистрировать</button>
                </div>

            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>